"""Auto-PR generator V8 — creates fix suggestion PRs from QVC scan results.

QVC NEVER auto-modifies code. PRs contain fix suggestion descriptions only.
Developers/AI Agents review and implement fixes manually.
"""

import json
from pathlib import Path
from dataclasses import dataclass, field


@dataclass
class AutoPRConfig:
    """Configuration for auto-PR generation"""
    min_confidence: float = 0.90  # Only ≥90% bugs trigger PR
    max_bugs_in_pr: int = 10  # Cap PR size
    pr_title_prefix: str = "[QVC]"
    pr_label: str = "qvc-review"
    include_fix_suggestions: bool = True


@dataclass
class FixSuggestion:
    """A single fix suggestion from QVC scan"""
    bug_id: str
    file_path: str
    line: int
    title: str
    description: str
    confidence: float
    severity: str
    fix_suggestion: str = ""
    blindspot_type: str = ""


def extract_high_confidence_bugs(scan_result_path: Path, min_confidence: float = 0.90) -> list[FixSuggestion]:
    """Extract only high-confidence bugs from JSON scan result"""
    bugs = []
    try:
        with open(scan_result_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return bugs

    # Handle both list format and dict format
    items = data if isinstance(data, list) else data.get("bugs", [])
    for item in items:
        confidence = item.get("confidence", 0)
        if confidence >= min_confidence:
            bugs.append(FixSuggestion(
                bug_id=item.get("id", ""),
                file_path=item.get("file_path", ""),
                line=item.get("line_start", 1),
                title=item.get("title", ""),
                description=item.get("description", ""),
                confidence=confidence,
                severity=item.get("severity", "unknown"),
                fix_suggestion=item.get("fix_suggestion", ""),
                blindspot_type=item.get("blindspot_type", ""),
            ))
    return bugs


def generate_pr_body(bugs: list[FixSuggestion], scan_summary: dict = None) -> str:
    """Generate a clear, actionable PR description from bug list"""
    if not bugs:
        return ""

    fatal = [b for b in bugs if b.severity == "fatal"]
    severe = [b for b in bugs if b.severity == "severe"]
    moderate = [b for b in bugs if b.severity == "moderate"]

    lines = [
        f"## QVC External Review — Found {len(bugs)} High-Confidence Issues",
        "",
        "> QVC is an AI Agent blind spot detector. It reviews code without modifying it.",
        "> These issues were NOT detected by AI self-review — they fall in AI structural blind spots.",
        "",
        "### Summary",
        "",
        f"| Severity | Count |",
        f"|----------|------:|",
    ]
    if fatal:
        lines.append(f"| Fatal | {len(fatal)} |")
    if severe:
        lines.append(f"| Severe | {len(severe)} |")
    if moderate:
        lines.append(f"| Moderate | {len(moderate)} |")
    lines.append("")

    # Detailed bugs
    lines.append("### Issues Found")
    lines.append("")
    for i, bug in enumerate(bugs[:10], 1):  # Cap at 10 for readability
        severity_emoji = "red_circle" if bug.severity == "fatal" else "orange_circle" if bug.severity == "severe" else "yellow_circle"
        lines.append(f"#### {severity_emoji} #{i}: {bug.title}")
        lines.append(f"- **File**: `{bug.file_path}:{bug.line}`")
        lines.append(f"- **Confidence**: {bug.confidence:.0%}")
        if bug.blindspot_type:
            lines.append(f"- **AI Blindspot**: {bug.blindspot_type}")
        lines.append(f"- **Description**: {bug.description}")
        if bug.fix_suggestion:
            lines.append(f"- **Fix suggestion**: {bug.fix_suggestion}")
        lines.append("")

    if len(bugs) > 10:
        lines.append(f"*...and {len(bugs) - 10} more. See full QVC report for details.*")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by [QVC](https://github.com/ericwuname/qvc-overseer) — the AI Agent external overseer.*")
    lines.append("*QVC never modifies code. These are review suggestions for human/AI evaluation.*")

    return "\n".join(lines)


def generate_pr_title(bugs: list[FixSuggestion]) -> str:
    """Generate a concise PR title"""
    fatal = sum(1 for b in bugs if b.severity == "fatal")
    severe = sum(1 for b in bugs if b.severity == "severe")

    parts = []
    if fatal:
        parts.append(f"{fatal} fatal")
    if severe:
        parts.append(f"{severe} severe")

    if parts:
        return f"[QVC] Found {', '.join(parts)} bugs — external review"
    return f"[QVC] Found {len(bugs)} high-confidence issues"


def should_create_pr(bugs: list[FixSuggestion]) -> bool:
    """Decide whether bugs warrant a PR"""
    if not bugs:
        return False
    # Don't create PRs for only moderate issues
    fatal_or_severe = [b for b in bugs if b.severity in ("fatal", "severe")]
    return len(fatal_or_severe) > 0


# CLI entry point for use in GitHub Actions
def main():
    import sys
    import os

    scan_file = os.environ.get("QVC_SCAN_RESULT", "qvc-report.json")
    min_conf = float(os.environ.get("QVC_MIN_CONFIDENCE", "0.90"))

    bugs = extract_high_confidence_bugs(Path(scan_file), min_conf)
    if not bugs or not should_create_pr(bugs):
        print(f"No high-confidence bugs to create PR for (scanned {scan_file})")
        sys.exit(0)

    title = generate_pr_title(bugs)
    body = generate_pr_body(bugs)

    # Output for GitHub Actions
    with open("qvc-pr-title.txt", "w") as f:
        f.write(title)
    with open("qvc-pr-body.md", "w") as f:
        f.write(body)

    print(f"PR ready: {title}")
    print(f"Bugs: {len(bugs)}")


if __name__ == "__main__":
    main()
