"""Protocol Generator — writes AGENTS.md QVC protocol block."""

from pathlib import Path

AGENTS_MD_BLOCK = """
<!-- QVC PROTOCOL — auto-generated by qvc setup -->

## QVC: External Code Review

This project uses QVC (QA of Vebe Coding) for external code review.
QVC is an external overseer that finds bugs your AI Agent missed in self-review.

### Commands
- When the user says **"fix qvc"** or **"qvc tasks"**: read `.qvc/tasks/pending.md` and fix all listed issues
- When the user says **"qvc status"**: read `.qvc/tasks/status.json` and report task state
- When the user says **"scan with qvc"**: run `qvc scan .` and process the results

### After fixing issues
Report to the user in 3-5 lines:
1. How many issues QVC found
2. How many you fixed
3. Which ones were structural blind spots (AI self-review could not detect them)

### Important
- QVC never modifies code itself — it only reports issues
- The `.qvc/tasks/pending.md` file is the handoff point between QVC and you
- Fix issues, then the user can re-scan to verify

<!-- END QVC PROTOCOL -->
"""

CURSORRULES_BLOCK = """
# QVC Protocol
When user says "fix qvc" or "qvc tasks", read .qvc/tasks/pending.md and fix all issues.
After fixing, report: what QVC found, what you fixed, which were blind spots.
"""


class ProtocolGenerator:
    """Generates protocol files so AI Agents know how to work with QVC."""

    @staticmethod
    def setup(project_root: Path, force: bool = False) -> dict:
        """Initialize QVC protocol in project. Returns summary of actions."""
        result = {"agents_md": False, "cursorrules": False, "qvc_dir": False}

        project_root = Path(project_root)

        # Create .qvc/ dir
        qvc_dir = project_root / ".qvc"
        tasks_dir = qvc_dir / "tasks"
        if not tasks_dir.exists():
            tasks_dir.mkdir(parents=True, exist_ok=True)
            result["qvc_dir"] = True

        # Write/append AGENTS.md
        agents_path = project_root / "AGENTS.md"
        if not agents_path.exists() or force:
            existing = ""
            if agents_path.exists():
                existing = agents_path.read_text(encoding="utf-8")
            if "QVC PROTOCOL" not in existing:
                new_content = existing.rstrip() + AGENTS_MD_BLOCK
                agents_path.write_text(new_content, encoding="utf-8")
                result["agents_md"] = True

        # Write .cursorrules (for Cursor users)
        cursor_path = project_root / ".cursorrules"
        if not cursor_path.exists():
            cursor_path.write_text(CURSORRULES_BLOCK, encoding="utf-8")
            result["cursorrules"] = True

        return result
